services:
    acme.demo.controller:
        class: rivertown\LCMSForum\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'